name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]
        redis-version: [5, 6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy pytest pytest-cov pytest-asyncio codecov msgpack ujson
          pip install -r requirements.txt
          pip install .
      - name: Lint
        run: |
          mypy .
          flake8 . --count --show-source --statistics
          isort -c .
          black .
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Test
        run: |
          pytest --cov --cov-report=xml
      - name: Publish coverage
        run: |
          codecov -f coverage.xml
